"""Accent Letters for Sublime Text — https://accentletters.wiki/

Two commands in the command palette:

  Accent Letters: Insert Accented Letter   — pick from 682 letters, typed at every cursor.
  Accent Letters: Remove Accents           — rewrite the selection without its accents.

Sublime Text 4 only. The package declares Python 3.8 in .python-version; ST3's plugin host is
Python 3.3, which has no f-strings, and ST3 has been end-of-life for years.
"""

import json
import os

import sublime
import sublime_plugin

from .accents import remove_accents

HERE = os.path.dirname(os.path.abspath(__file__))
SETTINGS = 'AccentLetters.sublime-settings'

_letters = None


def letters():
    """The 682 letters, read once per session.

    Generated by extension/build.mjs from Unicode 16.0.0 and CLDR 48.2.0 — the same data as the
    Accent Letters website and every other add-on, so a letter cannot differ between them.

    sublime.load_resource rather than open(): a package installed by Package Control is a ZIP
    (.sublime-package), and there is no file on disk to open. load_resource reads out of the
    archive and out of a plain folder alike, which is what makes the package work either way.
    """
    global _letters
    if _letters is None:
        package = os.path.basename(HERE)
        raw = sublime.load_resource('Packages/{}/letters.json'.format(package))
        _letters = json.loads(raw)
    return _letters


def options():
    """The two settings, with the same defaults every other Accent Letters surface has."""
    settings = sublime.load_settings(SETTINGS)
    return {
        'special': bool(settings.get('convert_special', True)),
        'german': settings.get('german_style', 'drop') == 'spell',
    }


def rows(data):
    """One quick-panel entry per letter.

    Sublime matches a list entry against EVERY string in it and displays every string, so the
    three lines are ordered by what is worth reading: the letter, then its name and codes, then
    the languages. The rest of the shared search haystack — "two dots", "going up", the HTML
    entity — is appended to the third line, where the panel truncates it out of sight while still
    matching on it. That is how a query nobody would want to read stays searchable.
    """
    names = data.get('langs', {})
    out = []
    for letter in data['letters']:
        codes = [c for c in ('U+' + letter['u'], letter.get('a')) if c]
        languages = [names.get(code, code) for code in letter.get('l', [])]
        shown = ', '.join(languages[:5])
        if len(languages) > 5:
            shown += ' +{}'.format(len(languages) - 5)

        # Whatever the first two lines already say is dropped from the tail, so the visible part of
        # line three is languages rather than a repeat of the name.
        seen = ' '.join([letter['c'], letter['d'], letter['n']] + codes + languages).lower()
        tail = ' '.join(w for w in letter['t'].split() if w not in seen.split())

        # A letter no language in CLDR uses — ǡ, say — has no languages AND nothing left in the
        # tail once the name above is discounted, which would leave the third line blank. The
        # accent marks are what is worth saying about those, and the Unicode name is the backstop.
        lead = shown or letter.get('m') or letter['n']

        out.append([
            letter['c'],
            '{} · {}'.format(letter['d'], ' · '.join(codes)),
            '{}{}'.format(lead, '  ' + tail if tail else ''),
        ])
    return out


class AccentLettersInsertCommand(sublime_plugin.TextCommand):
    """Pick a letter and type it at every cursor."""

    def run(self, edit):
        try:
            data = letters()
        except Exception as error:
            sublime.error_message('Accent Letters could not read its letter data: {}'.format(error))
            return

        chars = [letter['c'] for letter in data['letters']]
        window = self.view.window()

        def chosen(index):
            if index < 0:
                return
            # NOT self.view.insert(edit, ...): the `edit` token above is dead by the time this
            # callback runs, because the quick panel is asynchronous. The built-in insert command
            # takes a fresh one, and handles multiple cursors the way typing does.
            self.view.run_command('insert', {'characters': chars[index]})

        window.show_quick_panel(rows(data), chosen, sublime.KEEP_OPEN_ON_FOCUS_LOST)


class AccentLettersRemoveCommand(sublime_plugin.TextCommand):
    """Rewrite each selection without its accents."""

    def run(self, edit):
        regions = [region for region in self.view.sel() if not region.empty()]
        if not regions:
            # Rewriting the whole file because nothing was selected is not a mistake worth risking.
            sublime.status_message('Accent Letters: select the text you want to change first')
            return

        opts = options()
        edits = []
        for region in regions:
            before = self.view.substr(region)
            after = remove_accents(before, special=opts['special'], german=opts['german'])
            if after != before:
                edits.append((region, after))

        if not edits:
            sublime.status_message('Accent Letters: there are no accents in the selected text')
            return

        # Back to front: replacing a region shifts everything after it, so working forwards would
        # apply the second edit at the wrong offset as soon as the first changed the length.
        for region, after in sorted(edits, key=lambda pair: pair[0].begin(), reverse=True):
            self.view.replace(edit, region, after)

        sublime.status_message('Accent Letters: removed accents in {} selection{}'.format(
            len(edits), '' if len(edits) == 1 else 's'))

    def is_enabled(self):
        return any(not region.empty() for region in self.view.sel())
